### ISSUE TITLE
Link instead of page/content injection

### ISSUE THREAD

**Issue by prinla** [getgrav/grav-plugin-page-inject#10] opened 2017-01-29 14:08 UTC
Similar problem to https://github.com/getgrav/grav-plugin-page-inject/issues/4

Two different websites give me problems with the injection:

`[plugin:page-inject](/shop)`
is not resolved but converted into:
`<a href="de/shop">plugin:page-inject</a>`

`[plugin:content-inject](/mallorca/santa-ponsa)`
is not resolved but converted into:
`<a href="de/mallorca/santa-ponsa">plugin:content-inject</a>`

What is really strange is that the second example is from a website where the plugin used to work... 
but I realized it only now that it's broken... as I don't go on that page quite often to check it...
So any update of the core, the admin or another plugin might have caused a problem...
But I can't tell anymore when it happened. Unfortunately :(

On both websites I use the newest Grav v1.1.14 and Admin v1.2.9

**Comment by prinla** [comment] 2017-01-29 14:26
Indead I just checked an older backup of the website where it use to work...
The backup has not been updated and it still works there...
On this one run Grav v1.0.10 and Admin v1.0.9 with your version Page Inject v1.1.1

So somewhere between Grav v1.0.10 + Admin v1.0.9 + Page Inject v1.1.1
and Grav v1.1.14 + Admin v1.2.9 + Page Inject v1.2.0
lies the problem :)

ADDED:
I just installed your old version on the actual websites and it doesn't work neither...
So nothing to do with your update :)

**Comment by flaviocopes** [comment] 2017-01-30 18:33
I just checked and the plugins works fine. My guess is the plugin is enabled but not **ACTIVE** https://github.com/getgrav/grav-plugin-page-inject#config-defaults

**Comment by prinla** [comment] 2017-02-01 22:13
Sorry but the plugin is enabled and active...
Maybe it's because the site is multilingual?
The open issue No.#9 has also such a problem...

**Comment by jwillp** [comment] 2017-03-29 19:58
It seems that there is a problem with multilanguages. 
At ```page-inject.php:86```
```php
$inject = $page->find($page_path);
```
It always seems to return null if the ```$page_path``` variable contains a language prefix.
Therefore I think line 83 should be replaced by uncommenting line 84 to use the $relative paramter.
Looks like it works with this change.

**Comment by moabi** [comment] 2017-04-06 13:04
I do confirm the fix at line 84
`$page_path = Uri::convertUrl($page, $page_path, 'link', false, true);`
does makes this plugin works with multilingual

**Comment by tomhung** [comment] 2017-06-09 18:52
I had the same problem with multilingual.  The fix was to comment line 83 and uncomment 84.  Please commit to head.

**Comment by the4thamigo-uk** [comment] 2017-09-28 13:07
Is this fix going to be committed? We are also hitting this issue

**Comment by rhukster** [comment] 2017-09-28 13:13
I’ll look at this today. Got some releases planned anyway.

**Comment by Bokelmann** [comment] 2017-10-17 05:43
Dosen't work yet?

**Comment by Bokelmann** [comment] 2017-12-12 09:59
I tried to use the plugin in a custom-html Gantry 5-particle. And it didn't work tho I enabled the processing options in settings of the particle. The syntax worked fine in a regular page.
Can't say enough how awesome this plugin is.

**Comment by Hendrik-Koehler** [comment] 2018-09-23 00:20
Hi there,
started with same problem here with Page Inject Version 1.3.0 and current GRAV installation 1.5.0.
Fresh install. 
The fix above is incorporated in version 1.3.0.
However, the markdown is only rendered as link text.
Tested in a regular and in a modular page, without other content in the page.

BUT: As soon as  I add template information, it works, even with an basically empty template.

When trying to reproduce this it was even working without template.
No big deal, but perhaps helpful to know...

**Comment by Lamecarlate** [comment] 2018-09-23 06:07
Hello,
same problem (link instead of injection), and, strange enough, it works on localhost but not in production… The files are exactly the same because I deploy with git, except for config ones.

If my problem is very different from the ones in this issue, tell me, I'll open another one :)

I tracked the differences between system.yaml for localhost and prod:
- custom_base_url: different of course
- never_cache_twig: `false` on localhost, `true` otherwise
- twig.cache: `false` on localhost
- twig.debug: `true` on localhost
- assets.css_pipeline & js_pipeline: `false` on localhost, `true` otherwise
- errors.display & debugger.enabled: well, I don't think there is a link here

So, well, I don't know what could be the culprit here. 

In logs, there is no much help. Well, there is a thing: 

> grav.CRITICAL: Template "recipe.atom.twig" is not defined.

"recipe.twig" is the template used in the would-be injected page (recipe.md), this template exists. Not recipe.atom.twig (or recipe.rss.twig), and I don't see why they would exist… I have feed.rss.twig & feed.atom.twig templates.

And why am I not having this problem on localhost?

If anybody has a clue… Thanks!

**Closed as completed** 2019-04-15 23:06 UTC
Labels: fixed in devleop
